name: SBOM
on:
  release: # zizmor: ignore[concurrency-limits] - release events are inherently serialised
    types: [published]
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  sbom:
    name: SBOM
    permissions:
      actions: read # Required by anchore/sbom-action to read workflow run context.
      contents: write # Required to upload the SBOM as a release asset.
    uses: mozilla/ssdlc-actions/.github/workflows/ssdlc-sbom.yml@aa759c845c83060e2473fd8df60f9f408e34675d # v1.2
    with:
      sbom_name: ${{ github.event.release.tag_name || github.sha }}
